Repository AY2324S2-CS2113T-T09-4/tp, pull requests merged in 2024-04, with the labels that each got.

#122 cleanup validation for gym saving
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymStation.java
Labels: type.Enhancement, severity.Medium

#123 Add appointment, refactor magic numbers and strings
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/HealthConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/HealthList.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
  src/test/java/workouts/GymTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: type.Epic, type.Enhancement, priority.High

#125 Merge to master for week 11 tracking
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/HealthConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Filters.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/PeriodTest.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
  src/test/java/workouts/GymTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#126 Add Integration Test for Gym and Run
  src/main/java/constants/ErrorConstant.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
Labels: type.Enhancement

#127 Finalise storage mechanism and update UG
  docs/UserGuide.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/DataType.java
  src/main/java/utility/Parser.java
  src/main/java/workouts/WorkoutList.java
Labels: type.Epic, type.Enhancement, priority.High, severity.High

#128 Abstract methods, add integration tests, update DG
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/ui/Output.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/test/java/ui/IntegrationTest.java
Labels: type.Enhancement

#129 Add Gym into DG
  docs/DeveloperGuide.md
  src/main/java/constants/UiConstant.java
  src/main/java/health/HealthList.java
  src/main/java/ui/Handler.java
  src/main/java/workouts/WorkoutList.java
Labels: type.Enhancement, priority.High

#130 Add missing documentation in Health, Add architecture diagram in DG
  docs/DeveloperGuide.md
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/test/java/health/AppointmentTest.java
  src/test/java/health/PeriodTest.java
Labels: type.Enhancement, priority.High

#131 Update DG
  docs/DeveloperGuide.md
Labels: priority.High

#132 Finalise Storage
  src/main/java/storage/DataFile.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Parser.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/workouts/GymTest.java
Labels: type.Epic, type.Enhancement, priority.High, severity.High

#136 add Sequence Diagram for Gym
  src/main/java/ui/Handler.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/WorkoutList.java
Labels: type.Story, priority.High

#135 Update DG and add sequence diagrams
  docs/DeveloperGuide.md
  docs/img/run_sequence_diagram.png
  docs/img/ui_class_diagram.png
  docs/img/workout_class_diagram.png
  src/main/java/storage/DataFile.java
  src/main/java/storage/DataType.java
  src/main/java/utility/Filters.java
Labels: type.Enhancement, priority.High

#137 Merge to master for UG and DG tracking
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/img/appointment_sequence.png
  docs/img/architecture_diagram.png
  docs/img/bmi_sequence.png
  docs/img/health_package.png
  docs/img/period_prediction.png
  docs/img/period_sequence.png
  docs/img/run_sequence_diagram.png
  docs/img/ui_class_diagram.png
  docs/img/workout_class_diagram.png
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/DataType.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Filters.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/AppointmentTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/GymTest.java
Labels: type.Enhancement, priority.High

#144 Make storage more defensive
  .gitignore
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/storage/DataFile.java
  src/test/java/storage/DataFileTest.java
  src/test/java/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, type.Enhancement, priority.High, severity.High

#145 update dg and ug for workouts
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/health_package.png
  docs/img/run_sequence_diagram.png
  docs/img/run_validation_sequence_diagram.png
  docs/img/ui_class_diagram.png
  docs/img/workout_class_diagram.png
  docs/puml/run_sequence_diagram.puml
  docs/puml/run_validation_sequence_diagram.puml
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Run.java
  src/test/java/ui/OutputTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.High

#154 Fix table spacing
  docs/UserGuide.md
Labels: type.Bug

#158 fix user guide with new formatting
  docs/UserGuide.md
Labels: type.Bug

#182 Update 2101 UG
  docs/CS2101/UserGuide_2101.md
  docs/CS2101/img_2101/windows_cmd.png
Labels: priority.High

#207 Fixed issues based on PED
  docs/CS2101/UserGuide_2101.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/HealthConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
Labels: type.Enhancement, type.Bug, priority.High

#211 Update JUnit test ccode
  docs/UserGuide.md
  src/main/java/constants/UiConstant.java
  src/main/java/storage/DataFile.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Filters.java
  src/main/java/utility/Parser.java
  src/test/java/storage/DataFileTest.java
Labels: type.Epic, priority.High, severity.High

#210 Add more min max validation, fix spacing, update UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/adding_appointment.png
  docs/img/adding_bmi.png
  docs/img/adding_gym.png
  docs/img/adding_period.png
  docs/img/adding_runs.png
  docs/img/deleting.png
  docs/img/exit_bot.png
  docs/img/start_prompt.png
  docs/img/viewing_help.png
  docs/img/viewing_history.png
  docs/img/viewing_latest.png
  docs/img/viewing_prediction.png
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Run.java
  src/test/java/health/PeriodTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
Labels: priority.High, severity.High

#212 update dg and ug, update errors, cleanup
  docs/CS2101/UserGuide_2101.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/gym_class_diagram.png
  docs/img/handler_sequence_diagram.png
  docs/img/logo.jpg
  docs/img/workoutlist_class_diagram.png
  docs/puml/gym_class_diagram.puml
  docs/puml/handler_sequence_diagram.puml
  docs/puml/workoutlist_class_diagram.puml
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/utility/CustomExceptions.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/OutputTest.java
Labels: type.Enhancement, priority.Medium

#213 Remove Static to Non-Static and set Methods as Protected
  docs/UserGuide.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/seedu/pulsepilot/PulsePilot.java
  src/main/java/storage/DataFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/AppointmentTest.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/storage/DataFileTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: type.Epic, type.Enhancement, priority.Medium, severity.Medium

#214 Update User Guide and Health Constant
  docs/UserGuide.md
  docs/img/correct_command.png
  docs/img/extra_newline_error_command.png
  docs/img/extra_space_error_command.png
  src/main/java/constants/HealthConstant.java
Labels: type.Enhancement, priority.Low, severity.Low

#219 Update UG, Fix bugs for Health
  docs/UserGuide.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/HealthConstant.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/storage/DataFile.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/test/java/health/AppointmentTest.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/storage/DataFileTest.java
  src/test/java/ui/OutputTest.java
Labels: type.Enhancement, type.Bug, priority.High, severity.Medium

#221 Change Workout formatting for Print History
  src/main/java/constants/WorkoutConstant.java
  src/main/java/workouts/Gym.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: priority.High

#222 Finalise UG
  docs/UserGuide.md
  docs/img/output/accepting_commands.png
  docs/img/output/colour_not_rendered.png
  docs/img/output/correct_colour_render.png
  docs/img/output/data_corruption.png
  docs/img/output/missing_files.png
  docs/img/output/viewing_help.png
  docs/img/output/viewing_history.png
  docs/img/output/wrong_username.png
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Run.java
Labels: type.Epic, type.Enhancement, priority.High, severity.High

#225 write manual testing, add more validation, remove refs in dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/output/shutdown.png
  docs/img/sequence_diagrams/gym_overall_sequence_diagram.png
  docs/img/sequence_diagrams/gym_station_sequence_diagram.png
  docs/img/sequence_diagrams/handler_sequence_diagram.png
  docs/img/sequence_diagrams/run_sequence_diagram.png
  docs/puml/sequence_diagrams/gym_parseGymStationInput_sequence_diagram.puml
  docs/puml/sequence_diagrams/gym_sequence.puml
  docs/puml/sequence_diagrams/gym_station_sequence.puml
  docs/puml/sequence_diagrams/run_sequence_diagram.puml
  src/main/java/constants/ErrorConstant.java
  src/main/java/health/HealthList.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/OutputTest.java
Labels: priority.Medium

#234 add delete and storage to dg
  docs/DeveloperGuide.md
  docs/img/sequence_diagrams/delete_sequence.png
  docs/img/sequence_diagrams/storage_sequence.png
  docs/puml/sequence_diagrams/delete_sequence.puml
  docs/puml/sequence_diagrams/storage_sequence.puml
  src/main/java/constants/UiConstant.java
Labels: priority.High

#239 add tests, fix ppp
  docs/img/class_diagrams/gym_class_diagram.png
  docs/puml/class_diagrams/gym_class_diagram.puml
  docs/team/johndoe.md
  docs/team/l5-z.md
  src/main/java/constants/ErrorConstant.java
  src/main/java/storage/DataFile.java
  src/main/java/ui/Handler.java
  src/main/java/workouts/GymSet.java
  src/test/java/storage/DataFileTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/workouts/GymTest.java
Labels: priority.Medium

#240 Validation
  docs/DeveloperGuide.md
  docs/img/sequence_diagrams/set_Cycle_Length.png
  docs/puml/sequence_diagrams/set_Cycle_Length.puml
  src/main/java/constants/ErrorConstant.java
  src/main/java/health/HealthList.java
  src/main/java/utility/Validation.java
  src/test/java/utility/ValidationTest.java
Labels: type.Enhancement

#241 finalise DG and add author tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/img/architecture_diagram.png
  docs/img/sequence_diagrams/gym_overall_sequence_diagram.png
  docs/img/sequence_diagrams/gym_station_sequence_diagram.png
  docs/img/sequence_diagrams/history_printHistory.png
  docs/img/sequence_diagrams/history_printLatest.png
  docs/img/sequence_diagrams/history_sequence.png
  docs/img/sequence_diagrams/history_unused.png
  docs/img/sequence_diagrams/latest_sequence.png
  docs/img/sequence_diagrams/prediction_sequence_diagram.png
  docs/img/sequence_diagrams/run_sequence_diagram.png
  docs/puml/architecture_diagram.puml
  docs/puml/sequence_diagrams/gym_sequence.puml
  docs/puml/sequence_diagrams/gym_station_sequence.puml
  docs/puml/sequence_diagrams/history_sequence.puml
  docs/puml/sequence_diagrams/latest_sequence.puml
  docs/puml/sequence_diagrams/period_prediction.puml
  docs/puml/sequence_diagrams/run_sequence_diagram.puml
Labels: priority.High

#243 cleanup WorkoutLists, Run and Workout
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/storage/DataFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/main/java/workouts/WorkoutLists.java
  src/test/java/storage/DataFileTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
  src/test/java/workouts/GymTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListsTest.java
Labels: type.Enhancement

#256 add group code review
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/CustomExceptions.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutLists.java
  src/test/java/health/PeriodTest.java
  src/test/java/helper/TestHelper.java
  src/test/java/storage/DataFileTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/IntegrationTest.java
  src/test/java/ui/OutputTest.java
Labels: type.Enhancement
