Repository AY2324S2-CS2113T-T09-4/tp, pull requests merged in 2024-03, with the labels that each got.

#19 Update bot outputs and add getRun method
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/CustomExceptions.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.High, severity.High

#20 Integrate V0.1 into V1.0
  src/main/java/health/BMI.java
  src/main/java/health/Health.java
  src/main/java/health/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Constant.java
  src/main/java/utility/CustomExceptions.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/WorkoutListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic

#23 Health - BMI
  src/main/java/health/BMI.java
  src/main/java/health/Health.java
  src/main/java/health/Parser.java
Labels: type.Story

#27 Add Run exception test and handling
  src/main/java/utility/Constant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: type.Task

#30 Storage
  src/main/java/storage/Storage.java
  src/test/java/storage/StorageTest.java
Labels: type.Story

#36 Update UG template
  docs/UserGuide.md
  src/main/java/health/Bmi.java
Labels: type.Epic, type.Task

#37 Add checkTypeOfExercise
  src/main/java/ui/Handler.java
  src/main/java/utility/Constant.java
  src/main/java/utility/CustomExceptions.java
  src/test/java/ui/HandlerTest.java
Labels: type.Enhancement

#38 Update Handler and UI
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Constant.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.High, severity.Medium

#48 Update commands and logging
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Command.java
  src/main/java/utility/Constant.java
  src/test/java/storage/LogFileTest.java
Labels: type.Task, priority.High, severity.High

#51 Refactor code, remove magic numbers
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Constant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/Run.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/storage/LogFileTest.java
  src/test/java/ui/HandlerTest.java
Labels: type.Task, priority.High, severity.High

#57 Merge Conflict Handled + Gym User Input + Gym History
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Constant.java
  src/main/java/utility/Filters.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: type.Epic, priority.High

#56 Update UserGuide and health package
  docs/UserGuide.md
  src/main/java/health/Bmi.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Constant.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
Labels: priority.High

#60 Update UG, add Javadoc, fix test case, refactor code
  .gitignore
  build.gradle
  docs/UserGuide.md
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/seedu/pulsepilot/PulsePilot.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Constant.java
  src/main/java/utility/CustomExceptions.java
  src/main/java/utility/Filters.java
  src/main/java/utility/Parser.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/PeriodTest.java
  src/test/java/seedu/pulsepilot/PulsePilotTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
Labels: type.Epic, type.Task, priority.High

#59 V1.0
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Constant.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Medium

#61 Add latest command, update UG
  docs/UserGuide.md
  src/main/java/health/Bmi.java
  src/main/java/health/HealthList.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Constant.java
  src/main/java/utility/Filters.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/OutputTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Epic, priority.High, severity.High

#63 Update UG, Add printLatest JUnit
  docs/UserGuide.md
  src/main/java/ui/Output.java
  src/main/java/utility/Constant.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/Run.java
  src/test/java/ui/OutputTest.java
Labels: type.Enhancement, priority.High, severity.Medium

#64 Update JUnit for Handler
  src/main/java/ui/Output.java
  src/main/java/utility/Constant.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
Labels: type.Epic, type.Task, priority.High, severity.High

#68 enable assertion
  .gitignore
  build.gradle
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/Period.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/HealthConstant.java
  src/main/java/utility/UiConstant.java
  src/main/java/utility/WorkoutConstant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/BmiTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: priority.Medium

#70 Assertions
  src/main/java/storage/Storage.java
Labels: type.Story

#88 Add skeleton code for data file
  src/main/java/storage/DataFile.java
  src/main/java/storage/Storage.java
  src/main/java/utility/CustomExceptions.java
  src/main/java/utility/UiConstant.java
Labels: type.Epic

#86 Add testCases for defensive enhancement
  src/main/java/ui/Handler.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/WorkoutConstant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/GymTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
Labels: type.Enhancement

#93 Period prediction
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/utility/HealthConstant.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story

#92 Add delete function and defensive code for latest and history
  src/main/java/health/HealthList.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/WorkoutListTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Epic, type.Enhancement, priority.Medium

#94 Add checkDateInput function
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/utility/Parser.java
  src/main/java/workouts/Run.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
Labels: type.Enhancement, priority.Medium

#95 Add Defensive Mechanism for Run
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/WorkoutConstant.java
  src/main/java/workouts/Run.java
  src/test/java/ui/HandlerTest.java
Labels: type.Enhancement, type.Bug

#98 Add Storage mechanism outline and reformat an existing command
  src/main/java/health/Appointment.java
  src/main/java/health/HealthList.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/DataType.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/HealthConstant.java
  src/main/java/utility/UiConstant.java
  src/test/java/ui/HandlerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Epic, type.Enhancement, type.Task, priority.High, severity.High

#100 Add Appointment
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Filters.java
  src/main/java/utility/HealthConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/UiConstant.java
  src/test/java/health/AppointmentTest.java
  src/test/java/ui/HandlerTest.java
Labels: type.Epic, type.Enhancement, priority.High

#102 Closes #87 - add ability to input varying weights in gymStation
  docs/DeveloperGuide.md
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/UiConstant.java
  src/main/java/utility/WorkoutConstant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/test/java/ui/OutputTest.java
  src/test/java/workouts/GymTest.java
  src/test/java/workouts/WorkoutListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.High

#103 Update storage machanism and refactor code
  docs/DeveloperGuide.md
  src/main/java/storage/DataFile.java
  src/main/java/storage/DataType.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/UiConstant.java
  src/test/java/ui/HandlerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Epic, type.Enhancement, type.Task, priority.High, severity.High

#104 Refactor health and include input validation
  docs/DeveloperGuide.md
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/Health.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Filters.java
  src/main/java/utility/HealthConstant.java
  src/main/java/utility/Parser.java
  src/main/java/workouts/Run.java
  src/test/java/health/AppointmentTest.java
  src/test/java/health/BmiTest.java
  src/test/java/health/PeriodTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.High, severity.High

#109 Add parser tests, refactor substring function
  src/main/java/ui/Handler.java
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/UiConstant.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/test/java/utility/ParserTest.java
Labels: type.Enhancement, priority.Medium

#111 Rewrite Delete and add tests
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/UiConstant.java
  src/test/java/utility/ParserTest.java
Labels: type.Enhancement, type.Bug, priority.Medium

#119 add Load and Save of Gym Object
  src/main/java/utility/ErrorConstant.java
  src/main/java/utility/Parser.java
  src/main/java/utility/WorkoutConstant.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymStation.java
  src/test/java/storage/StorageTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/workouts/GymTest.java
Labels: type.Enhancement, priority.High

#120 V1.1
  src/main/java/constants/ErrorConstant.java
  src/main/java/constants/HealthConstant.java
  src/main/java/constants/UiConstant.java
  src/main/java/constants/WorkoutConstant.java
  src/main/java/health/Appointment.java
  src/main/java/health/Bmi.java
  src/main/java/health/HealthList.java
  src/main/java/health/Period.java
  src/main/java/storage/DataFile.java
  src/main/java/storage/LogFile.java
  src/main/java/ui/Handler.java
  src/main/java/ui/Output.java
  src/main/java/utility/Command.java
  src/main/java/utility/Filters.java
  src/main/java/utility/Parser.java
  src/main/java/utility/Validation.java
  src/main/java/workouts/Gym.java
  src/main/java/workouts/GymSet.java
  src/main/java/workouts/GymStation.java
  src/main/java/workouts/Run.java
  src/main/java/workouts/Workout.java
  src/main/java/workouts/WorkoutList.java
  src/test/java/health/PeriodTest.java
  src/test/java/ui/HandlerTest.java
  src/test/java/ui/OutputTest.java
  src/test/java/utility/ParserTest.java
  src/test/java/utility/ValidationTest.java
  src/test/java/workouts/RunTest.java
  src/test/java/workouts/WorkoutListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium
